export interface IProject {
  id: string
  images: string[]
  technologies: string[]
}

export const projects = [
  {
    id: 'uniw',
    images: [
      '/projects/1/1.png',
      '/projects/1/2.png',
      '/projects/1/3.png',
      '/projects/1/4.png',
      '/projects/1/5.png',
      '/projects/1/6.png',
    ],
    technologies: [
      'React',
      'Next.js',
      'TypeScript',
      'Node.js',
      'PostgreSQL',
      'Styled Components',
      'Prisma',
    ],
  },
  {
    id: 'mandato-digital',
    images: ['/projects/2/1.png', '/projects/2/2.png'],
    technologies: [
      'React',
      'Next.js',
      'TypeScript',
      'Node.js',
      'MongoDB',
      'Tailwind CSS',
    ],
  },
  {
    id: 'landing-page-ebook',
    images: [
      '/projects/3/1.png',
      '/projects/3/2.png',
      '/projects/3/3.png',
      '/projects/3/4.png',
      '/projects/3/5.png',
      '/projects/3/6.png',
      '/projects/3/7.png',
    ],
    technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
  },
  {
    id: 'hungry-hub',
    images: [
      '/projects/4/1.png',
      '/projects/4/2.png',
      '/projects/4/3.png',
      '/projects/4/4.png',
      '/projects/4/5.png',
      '/projects/4/6.png',
    ],
    technologies: [
      'React',
      'JavaScript',
      'Node.js',
      'MongoDB',
      'Redux',
      'Material UI',
    ],
  },
  {
    id: 'quick-shop',
    images: [
      '/projects/5/1.png',
      '/projects/5/2.png',
      '/projects/5/3.png',
      '/projects/5/4.png',
      '/projects/5/5.png',
      '/projects/5/6.png',
    ],
    technologies: [
      'React',
      'Next.js',
      'TypeScript',
      'Node.js',
      'Stripe API',
      'Tailwind CSS',
    ],
  },
  {
    id: 'agencia-bmw',
    images: [
      '/projects/6/1.png',
      '/projects/6/2.png',
      '/projects/6/3.png',
      '/projects/6/4.png',
      '/projects/6/5.png',
      '/projects/6/6.png',
    ],
    technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
  },
  {
    id: 'aplicativo-uniw',
    images: [
      '/projects/7/1.png',
      '/projects/7/2.png',
      '/projects/7/3.png',
      '/projects/7/4.png',
      '/projects/7/5.png',
      '/projects/7/6.png',
    ],
    technologies: [
      'React Native',
      'TypeScript',
      'Redux',
      'Firebase',
      'WebSockets',
    ],
  },
  {
    id: 'portfolio-pessoal',
    images: [
      '/projects/8/1.png',
      '/projects/8/2.png',
      '/projects/8/3.png',
      '/projects/8/4.png',
      '/projects/8/5.png',
      '/projects/8/6.png',
    ],
    technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
  },
  {
    id: 'rifas',
    images: [
      '/projects/9/1.png',
      '/projects/9/2.png',
      '/projects/9/3.png',
      '/projects/9/4.png',
      '/projects/9/5.png',
      '/projects/9/6.png',
    ],
    technologies: [
      'React',
      'Next.js',
      'TypeScript',
      'Node.js',
      'PostgreSQL',
      'Styled Components',
    ],
  },
  {
    id: 'website-bmw',
    images: [
      '/projects/10/1.png',
      '/projects/10/2.png',
      '/projects/10/3.png',
      '/projects/10/4.png',
      '/projects/10/5.png',
      '/projects/10/6.png',
    ],
    technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
  },
  {
    id: 'agencia-marketing',
    images: [
      '/projects/11/1.png',
      '/projects/11/2.png',
      '/projects/11/3.png',
      '/projects/11/4.png',
      '/projects/11/5.png',
    ],
    technologies: [
      'React',
      'Next.js',
      'TypeScript',
      'Node.js',
      'Styled Components',
    ],
  },
  {
    id: 'site-fit',
    images: [
      '/projects/12/1.png',
      '/projects/12/2.png',
      '/projects/12/3.png',
      '/projects/12/4.png',
      '/projects/12/5.png',
      '/projects/12/6.png',
    ],
    technologies: ['React', 'JavaScript', 'Node.js', 'Express.js', 'MongoDB'],
  },
  {
    id: 'sistema-delivery',
    images: [
      '/projects/13/1.png',
      '/projects/13/2.png',
      '/projects/13/3.png',
      '/projects/13/4.png',
      '/projects/13/5.png',
      '/projects/13/6.png',
    ],
    technologies: [
      'React',
      'JavaScript',
      'Node.js',
      'Express.js',
      'PostgreSQL',
    ],
  },
  {
    id: 'sistema-tickets',
    images: [
      '/projects/14/1.png',
      '/projects/14/2.png',
      '/projects/14/3.png',
      '/projects/14/4.png',
      '/projects/14/5.png',
      '/projects/14/6.png',
    ],
    technologies: ['React', 'TypeScript', 'Node.js', 'Prisma', 'PostgreSQL'],
  },
  {
    id: 'sistema-atendimento',
    images: [
      '/projects/15/1.png',
      '/projects/15/2.png',
      '/projects/15/3.png',
      '/projects/15/4.png',
      '/projects/15/5.png',
    ],
    technologies: [
      'React',
      'TypeScript',
      'Node.js',
      'Express.js',
      'PostgreSQL',
    ],
  },
] satisfies IProject[]
